### ISSUE TITLE
Create a database class

### ISSUE THREAD

**Issue by cyvu** [cyvu/html-css#31]
We need a JavaScript class that handles the connection, execute queries and closes the connection.

Place the file in the following path:
(root)<code>/js/classes/</code>database.js

Since this will be server-sided, Node.js will be responsible for handling the class.

Testing:
($ indicates it should be run from the terminal)
- Create the database class (database.js)
- Create a testing file (test-file.js)
- Consider creating test data (see related issue)
- Import the database.js in the testing file (see w3school regarding JavaScript import)
- $: <code>cd js/classes</code>
- $: <code>node test-file.js</code> (can be kept next the database.js, for now)

The following requirements for the database class have to be met:
- [x] A variable for the connection 

Compose 4 methods; 
- [x] read
- [x] write
- [x] delete
- [x] update

**Comment by Xokketeer** [comment]
I did it twice

**Comment by cyvu** [comment]
all done
